[package]
name = "oscar"
version = "0.1.0"
authors = ["Mattias Cibien <mattias@mattiascibien.net>"]

[dependencies]
egg-mode = "0.12.0"
dotenv = "0.12.0"
log = "0.4.1"
env_logger = "0.5.10"
gotham = "0.2.1"
hyper = "0.11.27"
mime = "0.3.7"
